// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAky6pEWCIHIgTNpWIzU5MKtTis3U3gIk',
    appId: '1:1030043597808:web:43ee8f9a7a8ad868927b35',
    messagingSenderId: '1030043597808',
    projectId: 'finding-ruby',
    authDomain: 'finding-ruby.firebaseapp.com',
    storageBucket: 'finding-ruby.firebasestorage.app',
    measurementId: 'G-KSYJNWF6E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU07J9wAnqFBFZyvGW8VbD70ZNwfZYNF8',
    appId: '1:1030043597808:android:016539931edbbb5e927b35',
    messagingSenderId: '1030043597808',
    projectId: 'finding-ruby',
    storageBucket: 'finding-ruby.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKXAZbqbHDITBdIBjjZwZSo3Qkw9l5t4',
    appId: '1:1030043597808:ios:c93a23996a635a37927b35',
    messagingSenderId: '1030043597808',
    projectId: 'finding-ruby',
    storageBucket: 'finding-ruby.firebasestorage.app',
    iosBundleId: 'com.example.findingRuby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqKXAZbqbHDITBdIBjjZwZSo3Qkw9l5t4',
    appId: '1:1030043597808:ios:c93a23996a635a37927b35',
    messagingSenderId: '1030043597808',
    projectId: 'finding-ruby',
    storageBucket: 'finding-ruby.firebasestorage.app',
    iosBundleId: 'com.example.findingRuby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAky6pEWCIHIgTNpWIzU5MKtTis3U3gIk',
    appId: '1:1030043597808:web:d6b72130b2b59226927b35',
    messagingSenderId: '1030043597808',
    projectId: 'finding-ruby',
    authDomain: 'finding-ruby.firebaseapp.com',
    storageBucket: 'finding-ruby.firebasestorage.app',
    measurementId: 'G-R1W8V5XVQT',
  );
}
